import Head from "next/head";
import React from 'react'
import styled from "styled-components";
import Navbar from "@/components/Navbar";


export default function Home() {
    return (
      <>
        <Head>
          <title>Classic Game Hub</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
   
        <Header>    
            Sudoku
        </Header>
              
      </>
    );
  }

  const Header = styled.h1`
    font-size: 4vw;
    color: red;
  `