import Head from "next/head";
import React from 'react'
import styled from "styled-components";
import Navbar from "@/components/Navbar";

const ParentContainer = styled.div`
    display: flex;
    margin: 0vw;
    padding: 0vw;
    background-color: #bf8040 ;
    align-items: center;
    justify-content: center;
`

export default function Home() {
    return (
      <>
        <Head>
          <title>Classic Game Hub</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
   
        <ParentContainer>
          <iframe width={500} height={500} src="https://cdn.htmlgames.com/DailySudoku/"></iframe>
        </ParentContainer>    
        
              
      </>
    );
  }

