import Head from "next/head";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import styled from "styled-components";
import React, {useState} from 'react';


const ParentContainer = styled.div`
  padding: 0vw;
  margin: 0vw;
`




export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      
      <ParentContainer>
      <Navbar />
      </ParentContainer>
      
    </>
  );
}

const Styletext = styled.div`
  color: red;
  background: black;
  text-align: center;
`

const RightSection = styled.button`
background: red;
border: 2px solid black;
height: 300px;
width: 300px;
`

