import Head from "next/head";
//import Image from "next/image";
import Navbar from "@/components/Navbar";
import Gamebar from "@/components/Gamebar";

import styled from "styled-components";

import { useContext } from "react";
import Link from 'next/link';


const ParentContainer = styled.div`
  padding: 0vw;
  margin: 0vw;
  height: 100%;
`


export default function Home() {
  return (
    <>
      <Head>
        <title>Classic Game Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <ParentContainer>

    
      <Gamebar/>
    
  
    </ParentContainer>
   
      </>
  );
}



